apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  sourceNamespaces:
    - cert-manager
  roles:
    - name: read-sync
      description: read and sync privileges
      policies:
        - p, proj:argocd:read-sync, applications, get, argocd/*, allow
        - p, proj:argocd:read-sync, applications, sync, argocd/*, allow
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project to configure security applications
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/sadaramk/homelab.git
