---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

generators:
  # Cert Manager Helm chart Definition
  - cm-chart.yaml
resources:
  # Namespace
  - resources/namespace.yaml
  # Argo Project for cert-manager
  - argocd-proj.yaml
  # ArgoCD Application for cert-manager
  - argocd-app.yaml
