apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    # email: "$SECRET_ACME_EMAIL" #TODO For some reason this is not working
    email: "kal@netlabs.com.au"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-key
        selector:
          dnsZones:
            # - "$K3S_CLUSTER_DOMAIN_NAME"
            - "amtired.com"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # email: "$SECRET_ACME_EMAIL" #TODO For some reason this is not working
    email: "kal@netlabs.com.au"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          # Configure your DNS Provider here...
          # ---
          # cloudflare:
          #   email: your-email@address
          # API Key:
          #   apiKeySecretRef:
          #     name: cloudflare-api-key-secret
          #     key: api-key
          # - or -
          # API Token:
          #   apiTokenSecretRef:
          #     name: cloudflare-api-token-secret
          #     key: api-token
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
        selector:
          dnsZones:
            # - "$K3S_CLUSTER_DOMAIN_NAME"
            - "amtired.com"
