apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: http://localhost:6445/
  project: argocd
  source:
    path: kubernetes/apps/argocd
    repoURL: https://github.com/sadaramk/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
