collections:
  - name: community.general
    version: 7.0.1
  - name: ansible.utils
    version: 2.10.3
  - name: kubernetes.core
    version: 2.4.0
roles:
  - name: githubixx.cilium_cli
    version: 2.6.0+0.13.2
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
